# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/admin/bookings', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Admin::Booking. As you add validations to Admin::Booking, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { name: 'name', email: 'email@mail.ru', move_in: '10.01.2023', move_out: '12.01.2023', room_id: 24 }
  end

  let(:invalid_attributes) do
    { name: 'name', email: 'email@mail.ru', move_out: '12.01.2023', room_id: 24 }
  end

  let(:admin) do
    User.create! email: 'example@mail.ru', password: 'example'
  end

  before do
    login_as(admin)
    Room.create! room_name: 'name', long_description: 'desc', short_description: 'short', id: 24, price: 12
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Booking.create! valid_attributes
      get admin_bookings_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      booking = Booking.create! valid_attributes
      get admin_booking_url(booking)
      expect(response).to be_successful
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        { name: 'name', email: 'email@mail.ru', move_in: '10.01.2023', move_out: '12.01.2023', accepted: true, room_id: 24 }
      end

      it 'updates the requested admin_booking' do
        booking = Booking.create! valid_attributes
        patch admin_booking_url(booking), params: { booking: new_attributes }
        booking.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the admin_bookings' do
        booking = Booking.create! valid_attributes
        patch admin_booking_url(booking), params: { booking: new_attributes }
        booking.reload
        expect(response).to redirect_to(admin_bookings_url)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested admin_booking' do
      booking = Booking.create! valid_attributes
      expect do
        delete admin_booking_url(booking)
      end.to change(Booking, :count).by(-1)
    end

    it 'redirects to the admin_bookings list' do
      booking = Booking.create! valid_attributes
      delete admin_booking_url(booking)
      expect(response).to redirect_to(admin_bookings_url)
    end
  end
end
